language: node_js

node_js:
    - "node"
    # - "14"
    - "12"
    - "10"

sudo: false

git:
    submodules: false

before_script:
    - npm install -g forever

script:
    - forever start -c 'npm start' ./
    - npm test

after_script:
    - forever stopall
    # - npm run report-coveralls
    # - npm run report-codecov
