language: node_js

node_js:
    - "node"
    # - "14"
    - "12"
    - "10"

sudo: false

git:
    submodules: false

addons:
    firefox: "60.0.1"


before_script:
    - npm install selenium-webdriver@^3.6.0
    - npm install

script:
    - npm test

after_success:
    # - forever stopall
    - npm run report-coveralls
    - npm run report-codecov
